package user;

import exceptions.StrException;

public class Customer {
	private int id;
	private String name;
	private String phone;
	
	public Customer (int id, String name, String phone) throws StrException {
		this.id = id;
		this.setName(name);
		this.setPhone(phone);
	}
	
	public Customer (int id, String name) throws StrException {
		this.id = id;
		this.setName(name);
	}
	
	public String getName() {
		return name;
	}
	
	public void setName(String name) throws StrException {
		if (name != null && !name.trim().isEmpty() && name.matches("[a-zA-Z ]+") && (name.length() <= 100 && name.length() >= 3))
		{
			this.name = name;
		} else {
			throw new StrException("Nome de usuário inválido.");
		}
	}
	
	public String getPhone() {
		return phone;
	}
	public void setPhone(String phone) throws StrException {
		if (phone != null && phone.matches("\\(\\d{2}\\) \\d{5}-\\d{4}")) {
			this.phone = phone;
		} else {
			throw new StrException("Número de telefone inválido.");
		}
	}
}
